#ifndef DEVICEID_H
#define DEVICEID_H

enum {
  FUJI_DEVICEID_DISK            = 0x31,
  FUJI_DEVICEID_DISK_LAST       = 0x3F,
  FUJI_DEVICEID_PRINTER         = 0x40,
  FUJI_DEVICEID_PRINTER_LAST    = 0x43,
  FUJI_DEVICEID_APETIME         = 0x45,
  FUJI_DEVICEID_ASPEQT          = 0x46,
  FUJI_DEVICEID_SIO2BT_NET      = 0x4E,
  FUJI_DEVICEID_TYPE3POLL       = 0x4F,
  FUJI_DEVICEID_RS232           = 0x50,
  FUJI_DEVICEID_RS232_LAST      = 0x53,
  FUJI_DEVICEID_CPM             = 0x5A,
  FUJI_DEVICEID_CASSETTE        = 0x5F,
  FUJI_DEVICEID_PCLINK          = 0x6F,
  FUJI_DEVICEID_FUJINET         = 0x70,
  FUJI_DEVICEID_FN_NETWORK      = 0x71,
  FUJI_DEVICEID_FN_NETWORK_LAST = 0x78,
  FUJI_DEVICEID_MIDI            = 0x99,
  FUJI_DEVICEID_FILE            = 0xAA,
};

#define FUJI_DEVICEID_FN_VOICE          FUJI_DEVICEID_PRINTER_LAST
#define FUJI_DEVICEID_SIO2BT_SMART      FUJI_DEVICEID_APETIME // Doubles as APETime and "High Score Submission" to URL

#endif /* DEVICEID_H */
